/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'

const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/committees': typeof CommitteesRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/committees': typeof CommitteesRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/committees': typeof CommitteesRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/committees'
    | '/donate'
    | '/events'
    | '/faq'
    | '/mission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/committees'
    | '/donate'
    | '/events'
    | '/faq'
    | '/mission'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/committees'
    | '/donate'
    | '/events'
    | '/faq'
    | '/mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  CommitteesRoute: typeof CommitteesRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  MissionRoute: typeof MissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  CommitteesRoute: CommitteesRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  MissionRoute: MissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
